-- AlterTable
ALTER TABLE "organizations" ADD COLUMN     "address" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "faviconKey" TEXT,
ADD COLUMN     "logoKey" TEXT,
ADD COLUMN     "portalAllowDocUpload" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "portalAllowPasswordChange" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "portalAllowProfileEdit" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "portalEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "portalShowConsultant" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "portalShowContactInfo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "postalCode" TEXT,
ADD COLUMN     "primaryColor" TEXT,
ADD COLUMN     "secondaryColor" TEXT,
ADD COLUMN     "shortName" TEXT,
ADD COLUMN     "uploadAllowMultiple" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "uploadAllowReplace" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "uploadAllowedDocTypes" TEXT[] DEFAULT ARRAY['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']::TEXT[],
ADD COLUMN     "uploadAllowedImageTypes" TEXT[] DEFAULT ARRAY['image/jpeg', 'image/png', 'image/webp']::TEXT[],
ADD COLUMN     "uploadMaxFilesPerReq" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "uploadMaxSizeMb" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "uploadRequireApprovalForResubmit" BOOLEAN NOT NULL DEFAULT false;
